### ISSUE TITLE
react-components version is not pinned

### ISSUE THREAD

**Issue by grapegravity** [macropodhq/macropod-components#257]
Is there any rationale for this?

**Comment by jessta** [comment]
https://github.com/macropodhq/macropod-components/commit/d44ce2c353d1eb05fe6df1d3e8f177b2b7656875#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

Looks like it's just something that got missed.

**Comment by grapegravity** [comment]
This has been fixed.
