### ISSUE TITLE
Prompt component calls preventDefault() on a non-existent event in it's handleOk

### ISSUE THREAD

**Issue by jessta** [macropodhq/macropod-components#346]
https://github.com/macropodhq/macropod-components/blob/master/packages/prompt/index.jsx#L69

**Comment by ojame** [comment]
the prevent default is called up the tree: https://github.com/macropodhq/macropod-components/blob/master/packages/alert/index.jsx#L51

so safe to remove this?

**Comment by jessta** [comment]
This also happened recently with the modal.
Fixed it with: https://github.com/macropodhq/macropod-components/blob/master/packages/modal/index.jsx#L63-L65

It might be good to replace all uses of DOM events with an explicit check for the event. Since this is going to come up again as components get moved around.
